# Generated by Django 5.1.1 on 2024-09-16 15:59

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='cat_name'),
        ),
    ]
