# Generated by Django 5.1.1 on 2024-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
