# Generated by Django 5.1.1 on 2024-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='avatar.jpg', upload_to='categories/', verbose_name='Category Image'),
        ),
    ]
